<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.tpv</groupId>
    <artifactId>tpv-desktop</artifactId>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <javafx.version>21.0.4</javafx.version>
        <jackson.version>2.17.2</jackson.version>
        <junit.version>5.10.2</junit.version>
        <tpv.mode>auto</tpv.mode>
        <tpv.auto.login>false</tpv.auto.login>
        <tpv.auth.user></tpv.auth.user>
        <tpv.auth.pass></tpv.auth.pass>
        <tpv.kiosk.mode>false</tpv.kiosk.mode>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${jackson.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.8</version>
                <configuration>
                    <mainClass>com.tpv.desktop.App</mainClass>
                    <options>
                        <option>-Dtpv.mode=${tpv.mode}</option>
                        <option>-Dtpv.auto.login=${tpv.auto.login}</option>
                        <option>-Dtpv.auth.user=${tpv.auth.user}</option>
                        <option>-Dtpv.auth.pass=${tpv.auth.pass}</option>
                        <option>-Dtpv.kiosk.mode=${tpv.kiosk.mode}</option>
                    </options>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
